Update cosmic and mitelman DBs, add FusionGDB2 without weight
matq007/fusion-report pull request #47
Opened 2022-03-09 10:16 UTC by rannick

- Update COSMIC
- Update Mitelman
- Add FusionGDB2 with weight 0, as indicator: first step to upgrade from FusionGDB
- Create a "DB-timestep.txt" file in DB folder at download time for trace keeping
- Update documentation

- [x] Specify in detail the change
- [x] Make sure to follow guidelines in `docs` when adding database/tool
- [x] Documentation in `docs` is updated
- [ ] `CHANGELOG.md` is updated
- [x] `README` is updated

2022-03-09 20:24 UTC, matq007 approved these changes

2022-03-10 09:11 UTC, matq007 requested changes

2022-03-10 09:11 UTC, matq007 commented on requirements.txt
> +openpyxl==3.0.9
```suggestion
tqdm
colorlog
python-rapidjson
pyyaml>=4.2b1
Jinja2>=2.10
MarkupSafe
pandas
openpyxl
```

2022-03-10 09:24 UTC, rannick commented on requirements.txt
> +openpyxl==3.0.9
Applied with [99114df](https://github.com/matq007/fusion-report/pull/47/commits/99114df6b5fc5debbd2eb460c31810c853d7c7ca)

2022-03-16 15:24 UTC, merged